name: core
description: This package contains the core functionality for the cores project.
publish_to: none
version: 1.0.0


environment:
  sdk: ^3.7.2

resolution: workspace

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  simple_logger: ^1.10.0

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  freezed: ^3.0.6
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  very_good_analysis: ^7.0.0
