include: package:very_good_analysis/analysis_options.7.0.0.yaml
analyzer:
  errors:
    invalid_annotation_target: ignore
    one_member_abstracts: ignore
    public_member_api_docs: ignore
    use_setters_to_change_properties: ignore
