name: designsystem
description: "This package provides style definitions, themes, etc."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.7.2
  flutter: ^3.29.2

resolution: workspace

dependencies:
  core:
    path: ../core
  flutter:
    sdk: flutter
  theme_extensions_builder_annotation: ^4.0.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  flutter_test:
    sdk: flutter
  theme_extensions_builder: ^4.0.1
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_gen:
  output: lib/src/gen/assets
  assets:
    outputs:
      package_parameter_enabled: true
